stages:
  - lint
  - test
  - build
  - build_image

lint:
  stage: lint
  image: golang:buster
  script:
    - make lint_ci
  tags:
    - docker

test:
  stage: test
  image: golang:buster
  before_script:
    - apt-get update; apt-get install sysstat -y
  script:
    - make test
  tags:
    - docker

build:
  stage: build
  image: golang:buster
  script:
    - make build_ci
  tags:
    - docker
  artifacts:
    paths:
      - ./bin
    expire_in: 1d
  when: on_success

build_image:
  stage: build_image
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - /kaniko/executor --context . --dockerfile ./Deployments/Docker/Dockerfile --destination monitoring:$CI_COMMIT_TAG
  tags:
    - docker
  dependencies:
    - build
  when: manual
